summary: "Login"
description: "Login"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Accepts input..."
    required: true
    schema:
      type: "object"
      properties:
        username:
          type: "integer"
          format: "int64"
          example: 45
        password:
          type: "integer"
          format: "int64"
          example: 45
responses:
  405:
    description: "Invalid input"